FROM docker.io/debian:stable-slim AS build

ARG WOODPECKER_SERVER_VERSION="${WOODPECKER_SERVER_VERSION:-3.16.0}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        tar

# woodpecker-server

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/woodpecker-server

RUN curl --proto '=https' --tlsv1.3 \
        --location https://github.com/woodpecker-ci/woodpecker/releases/download/v${WOODPECKER_SERVER_VERSION}/woodpecker-server_linux_amd64.tar.gz \
        --output /usr/local/src/woodpecker-server/woodpecker-server_linux_amd64.tar.gz

RUN curl --proto '=https' --tlsv1.3 \
        --location https://github.com/woodpecker-ci/woodpecker/releases/download/v${WOODPECKER_SERVER_VERSION}/checksums.txt \
        --output /usr/local/src/woodpecker-server/checksums.txt

WORKDIR /usr/local/src/woodpecker-server
RUN sha256sum --ignore-missing --check checksums.txt

RUN tar --extract --gzip --file=/usr/local/src/woodpecker-server/woodpecker-server_linux_amd64.tar.gz --directory=/usr/local/src/woodpecker-server

RUN chmod 0755 /usr/local/src/woodpecker-server/woodpecker-server

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

ENV WOODPECKER_DATABASE_DATASOURCE="/var/local/woodpecker-server/db/woodpecker.sqlite" \
    WOODPECKER_DATABASE_DRIVER="sqlite3"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        procps

# woodpecker-server

COPY --from=build --chown=root:root /usr/local/src/woodpecker-server/woodpecker-server /usr/local/bin/woodpecker-server

# user and permissions

RUN groupadd --gid 10000 woodpecker && \
    useradd --comment 'woodpecker' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 woodpecker

RUN install --directory --owner=root --group=root --mode=0755 /var/local/woodpecker-server && \
    install --directory --owner=woodpecker --group=woodpecker --mode=0750 /var/local/woodpecker-server/db

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER woodpecker
STOPSIGNAL SIGINT

CMD ["/bin/bash", "/cmd.sh"]
