FROM docker.io/debian:stable-slim AS build

ARG BLOCKBOOK_VERSION="${BLOCKBOOK_VERSION:-0.5.0}"
ARG GO_CHECKSUM="${GO_CHECKSUM:-1153d3d50e0ac764b447adfe05c2bcf08e889d42a02e0fe0259bd47f6733ad7f}"
ARG GO_VERSION="${GO_VERSION:-1.26.4}"
ARG ROCKSDB_VERSION="${ROCKSDB_VERSION:-9.10.0}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        autoconf \
        automake \
        build-essential \
        ca-certificates \
        curl \
        git \
        gnupg \
        libbz2-dev \
        libgflags-dev \
        liblz4-dev \
        libsnappy-dev \
        libtool \
        libzmq3-dev \
        libzstd-dev \
        pkg-config \
        tar \
        zlib1g-dev

# go

ENV PATH="${PATH}:/usr/local/share/go/bin"

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/share/go \
    install --directory --owner=root --group=root --mode=0755 /usr/local/src/go

RUN curl --proto '=https' --tlsv1.3 \
        --location https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz \
        --output /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz

RUN curl --proto '=https' --tlsv1.3 \
        --location https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz.asc \
        --output /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.asc

# https://dl.google.com/linux/linux_signing_key.pub
COPY --chown=root:root gpg /root/gpg
RUN gpg --no-default-keyring --keyring /root/keyring.gpg --fingerprint
RUN for key in /root/gpg/*; do \
        gpg --no-default-keyring --keyring /root/keyring.gpg --batch --import ${key}; \
    done

RUN gpg --no-default-keyring --keyring /root/keyring.gpg --verify /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.asc /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz

RUN echo "${GO_CHECKSUM}  go${GO_VERSION}.linux-amd64.tar.gz" >/usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.sha256

WORKDIR /usr/local/src/go
RUN sha256sum --ignore-missing --check go${GO_VERSION}.linux-amd64.tar.gz.sha256

RUN tar --extract --gzip --file=/usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz --directory=/usr/local/share

# rocksdb

ENV CGO_CFLAGS="-I/usr/local/include/rocksdb" \
    CGO_LDFLAGS="-L/usr/local/share/rocksdb -lrocksdb -lstdc++ -lm -lz -ldl -lbz2 -lsnappy -llz4"

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/include/rocksdb \
    install --directory --owner=root --group=root --mode=0755 /usr/local/share/rocksdb \
    install --directory --owner=root --group=root --mode=0755 /usr/local/src/rocksdb

WORKDIR /usr/local/src
RUN git clone --depth 1 --branch v${ROCKSDB_VERSION} https://github.com/facebook/rocksdb.git

WORKDIR /usr/local/src/rocksdb
RUN CFLAGS=-fPIC CXXFLAGS=-fPIC make -j 4 release

RUN cp /usr/local/src/rocksdb/librock* /usr/local/share/rocksdb && \
    cp -r /usr/local/src/rocksdb/include/rocksdb/* /usr/local/include/rocksdb

# blockbook

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/share/blockbook \
    install --directory --owner=root --group=root --mode=0755 /usr/local/src/blockbook

WORKDIR /usr/local/src
RUN git clone --depth 1 --branch v${BLOCKBOOK_VERSION} https://github.com/trezor/blockbook.git

WORKDIR /usr/local/src/blockbook
RUN go build -tags rocksdb_7_7

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        jq \
        libsnappy-dev \
        libzmq3-dev \
        procps

# blockbook

COPY --from=build --chown=root:root /usr/local/src/blockbook/blockbook /usr/local/bin/blockbook
COPY --from=build --chown=root:root /usr/local/src/blockbook/static /usr/local/share/blockbook/static

# user and permissions

RUN groupadd --gid 10000 blockbook && \
    useradd --comment 'blockbook' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 blockbook

RUN install --directory --owner=root --group=root --mode=0755 /var/local/blockbook && \
    install --directory --owner=blockbook --group=blockbook --mode=0750 /var/local/blockbook/db

RUN install --directory --owner=blockbook --group=blockbook --mode=0750 /var/local/blockbook/config

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER blockbook

WORKDIR /usr/local/share/blockbook
CMD ["/bin/bash", "/cmd.sh"]
