FROM docker.io/debian:stable-slim AS build

ARG RUSTY_KASPA_VERSION="${RUSTY_KASPA_VERSION:-2.0.0}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        unzip

# rusty-kaspa

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/rusty-kaspa

RUN curl --proto '=https' --tlsv1.3 \
        --location https://github.com/kaspanet/rusty-kaspa/releases/download/v${RUSTY_KASPA_VERSION}/rusty-kaspa-v${RUSTY_KASPA_VERSION}-linux-amd64.zip \
        --output /usr/local/src/rusty-kaspa/rusty-kaspa-v${RUSTY_KASPA_VERSION}-linux-amd64.zip

RUN unzip /usr/local/src/rusty-kaspa/rusty-kaspa-v${RUSTY_KASPA_VERSION}-linux-amd64.zip -d /usr/local/src/rusty-kaspa/

RUN chmod 0755 /usr/local/src/rusty-kaspa/bin/kaspad

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        procps

# rusty-kaspa

COPY --from=build --chown=root:root /usr/local/src/rusty-kaspa/bin/kaspad /usr/local/bin/kaspad

# user and permissions

RUN groupadd --gid 10000 rusty-kaspa && \
    useradd --comment 'rusty-kaspa' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 rusty-kaspa

RUN install --directory --owner=root --group=root --mode=0755 /var/local/rusty-kaspa && \
    install --directory --owner=rusty-kaspa --group=rusty-kaspa --mode=0700 /var/local/rusty-kaspa/data && \
    install --directory --owner=rusty-kaspa --group=rusty-kaspa --mode=0700 /tmp/rusty-kaspa

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER rusty-kaspa
STOPSIGNAL SIGINT

CMD ["/bin/bash", "/cmd.sh"]
