FROM docker.io/debian:stable-slim AS build

ARG WOODPECKER_AGENT_VERSION="${WOODPECKER_AGENT_VERSION:-3.14.1}"
ARG WOODPECKER_PLUGIN_GIT="${WOODPECKER_PLUGIN_GIT:-2.9.1}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        tar

# woodpecker-agent

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/woodpecker-agent

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/woodpecker-ci/woodpecker/releases/download/v${WOODPECKER_AGENT_VERSION}/woodpecker-agent_linux_amd64.tar.gz \
        --output /usr/local/src/woodpecker-agent/woodpecker-agent_linux_amd64.tar.gz

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/woodpecker-ci/woodpecker/releases/download/v${WOODPECKER_AGENT_VERSION}/checksums.txt \
        --output /usr/local/src/woodpecker-agent/checksums.txt

WORKDIR /usr/local/src/woodpecker-agent
RUN sha256sum --ignore-missing --check checksums.txt

RUN tar --extract --gzip --file=/usr/local/src/woodpecker-agent/woodpecker-agent_linux_amd64.tar.gz --directory=/usr/local/src/woodpecker-agent

RUN chmod 0755 /usr/local/src/woodpecker-agent/woodpecker-agent

# plugin-git

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/plugin-git

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/woodpecker-ci/plugin-git/releases/download/${WOODPECKER_PLUGIN_GIT}/linux-amd64_plugin-git \
        --output /usr/local/src/plugin-git/linux-amd64_plugin-git

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/woodpecker-ci/plugin-git/releases/download/${WOODPECKER_PLUGIN_GIT}/checksums.txt \
        --output /usr/local/src/plugin-git/checksums.txt

WORKDIR /usr/local/src/plugin-git
RUN sha256sum --ignore-missing --check checksums.txt

RUN chmod 0755 /usr/local/src/plugin-git/linux-amd64_plugin-git

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        git-lfs \
        procps

# woodpecker-agent

COPY --from=build --chown=root:root /usr/local/src/woodpecker-agent/woodpecker-agent /usr/local/bin/woodpecker-agent

# plugin-git

COPY --from=build --chown=root:root /usr/local/src/plugin-git/linux-amd64_plugin-git /usr/local/bin/plugin-git

# user and permissions

RUN groupadd --gid 10000 woodpecker && \
    useradd --comment 'woodpecker' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 woodpecker

RUN install --directory --owner=root --group=root --mode=0755 /var/local/woodpecker-agent && \
    install --directory --owner=woodpecker --group=woodpecker --mode=0750 /var/local/woodpecker-agent/certs && \
    install --directory --owner=woodpecker --group=woodpecker --mode=0750 /var/local/woodpecker-agent/tmp

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER root
STOPSIGNAL SIGINT

CMD ["/bin/bash", "/cmd.sh"]
