FROM docker.io/debian:stable-slim AS build

ARG COSIGN_VERSION="${COSIGN_VERSION:-3.1.2}"
ARG HELM_VERSION="${HELM_VERSION:-4.2.3}"
ARG K0SCTL_VERSION="${K0SCTL_VERSION:-0.32.1}"
ARG K0S_VERSION="${K0S_VERSION:-1.36.2+k0s.0}"
ARG KUBECTL_VERSION="${KUBECTL_VERSION:-1.36.2}"
ARG KUBESOLOCTL_VERSION="${KUBESOLOCTL_VERSION:-1.1.9}"
ARG KUSTOMIZE_VERSION="${KUSTOMIZE_VERSION:-5.8.1}"
ARG YQ_VERSION="${YQ_VERSION:-4.53.3}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        tar

# cosign

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/cosign/${COSIGN_VERSION}

RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-linux-amd64 \
    --output /usr/local/src/cosign/${COSIGN_VERSION}/cosign-linux-amd64
RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-linux-amd64.sigstore.json \
    --output /usr/local/src/cosign/${COSIGN_VERSION}/cosign-linux-amd64.sigstore.json

RUN chmod +x /usr/local/src/cosign/${COSIGN_VERSION}/cosign-linux-amd64
RUN ln -s /usr/local/src/cosign/${COSIGN_VERSION}/cosign-linux-amd64 /usr/local/bin/cosign

RUN cosign verify-blob \
    --bundle /usr/local/src/cosign/${COSIGN_VERSION}/cosign-linux-amd64.sigstore.json \
    --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com \
    --certificate-oidc-issuer https://accounts.google.com \
    /usr/local/src/cosign/${COSIGN_VERSION}/cosign-linux-amd64
RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign_checksums.txt \
    --output /usr/local/src/cosign/${COSIGN_VERSION}/cosign_checksums.txt
RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign_checksums.txt.sigstore.json \
    --output /usr/local/src/cosign/${COSIGN_VERSION}/cosign_checksums.txt.sigstore.json

RUN cosign verify-blob \
    --bundle /usr/local/src/cosign/${COSIGN_VERSION}/cosign_checksums.txt.sigstore.json \
    --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com \
    --certificate-oidc-issuer https://accounts.google.com \
    /usr/local/src/cosign/${COSIGN_VERSION}/cosign_checksums.txt

WORKDIR /usr/local/src/cosign/${COSIGN_VERSION}
RUN sha256sum --ignore-missing --check cosign_checksums.txt

# helm

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/helm/${HELM_VERSION}

RUN curl --proto '=https' --tlsv1.3 \
    --location https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz \
    --output /usr/local/src/helm/${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz
RUN curl --proto '=https' --tlsv1.3 \
    --location https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256 \
    --output /usr/local/src/helm/${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256

RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.asc \
    --output /usr/local/src/helm/${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.asc
RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256.asc \
    --output /usr/local/src/helm/${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256.asc
RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/helm/helm/releases/download/v${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256sum.asc \
    --output /usr/local/src/helm/${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256sum.asc

COPY --chown=root:root gpg/helm /root/gpg/helm
RUN for key in /root/gpg/helm/*; do \
        gpg --no-default-keyring --keyring /root/helm.gpg --batch --import ${key}; \
    done
RUN gpg --no-default-keyring --keyring /root/helm.gpg --fingerprint

WORKDIR /usr/local/src/helm/${HELM_VERSION}

RUN gpg --no-default-keyring --keyring /root/helm.gpg --verify helm-v${HELM_VERSION}-linux-amd64.tar.gz.asc helm-v${HELM_VERSION}-linux-amd64.tar.gz
RUN gpg --no-default-keyring --keyring /root/helm.gpg --verify helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256.asc helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256
RUN echo "$(cat helm-v${HELM_VERSION}-linux-amd64.tar.gz.sha256)  helm-v${HELM_VERSION}-linux-amd64.tar.gz" | sha256sum --check -

RUN tar --extract --gzip --file=/usr/local/src/helm/${HELM_VERSION}/helm-v${HELM_VERSION}-linux-amd64.tar.gz --directory=/usr/local/src/helm/${HELM_VERSION} --no-same-owner
RUN chmod +x /usr/local/src/helm/${HELM_VERSION}/linux-amd64/helm
RUN ln -snf /usr/local/src/helm/${HELM_VERSION}/linux-amd64/helm /usr/local/bin/helm

# k0sctl

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/k0sctl/${K0SCTL_VERSION}

RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/k0sproject/k0sctl/releases/download/v${K0SCTL_VERSION}/checksums.txt \
    --output /usr/local/src/k0sctl/${K0SCTL_VERSION}/checksums.txt
RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/k0sproject/k0sctl/releases/download/v${K0SCTL_VERSION}/k0sctl-linux-amd64 \
    --output /usr/local/src/k0sctl/${K0SCTL_VERSION}/k0sctl-linux-amd64

WORKDIR /usr/local/src/k0sctl/${K0SCTL_VERSION}
RUN sha256sum --ignore-missing --check checksums.txt

RUN chmod +x /usr/local/src/k0sctl/${K0SCTL_VERSION}/k0sctl-linux-amd64
RUN ln -snf /usr/local/src/k0sctl/${K0SCTL_VERSION}/k0sctl-linux-amd64 /usr/local/bin/k0sctl

# k0s

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/k0s/${K0S_VERSION}

RUN ["/bin/bash", "-c", "curl --proto '=https' --tlsv1.3 --location https://github.com/k0sproject/k0s/releases/download/v${K0S_VERSION//+/%2B}/k0s-v${K0S_VERSION}-amd64 --output /usr/local/src/k0s/${K0S_VERSION}/k0s-v${K0S_VERSION}-amd64"]
RUN ["/bin/bash", "-c", "curl --proto '=https' --tlsv1.3 --location https://github.com/k0sproject/k0s/releases/download/v${K0S_VERSION//+/%2B}/k0s-v${K0S_VERSION}-amd64.sig --output /usr/local/src/k0s/${K0S_VERSION}/k0s-v${K0S_VERSION}-amd64.sig"]
RUN ["/bin/bash", "-c", "curl --proto '=https' --tlsv1.3 --location https://github.com/k0sproject/k0s/releases/download/v${K0S_VERSION//+/%2B}/cosign.pub --output /usr/local/src/k0s/${K0S_VERSION}/cosign.pub"]
RUN ["/bin/bash", "-c", "curl --proto '=https' --tlsv1.3 --location https://github.com/k0sproject/k0s/releases/download/v${K0S_VERSION//+/%2B}/sha256sums.txt --output /usr/local/src/k0s/${K0S_VERSION}/sha256sums.txt"]

RUN cosign verify-blob \
    --key /usr/local/src/k0s/${K0S_VERSION}/cosign.pub \
    --signature /usr/local/src/k0s/${K0S_VERSION}/k0s-v${K0S_VERSION}-amd64.sig \
    /usr/local/src/k0s/${K0S_VERSION}/k0s-v${K0S_VERSION}-amd64
WORKDIR /usr/local/src/k0s/${K0S_VERSION}
RUN sha256sum --ignore-missing --check sha256sums.txt

RUN chmod +x /usr/local/src/k0s/${K0S_VERSION}/k0s-v${K0S_VERSION}-amd64
RUN ln -snf /usr/local/src/k0s/${K0S_VERSION}/k0s-v${K0S_VERSION}-amd64 /usr/local/bin/k0s

# kubectl

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/kubectl/${KUBECTL_VERSION}

RUN curl --proto '=https' --tlsv1.3 \
    --location https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
    --output /usr/local/src/kubectl/${KUBECTL_VERSION}/kubectl
RUN curl --proto '=https' --tlsv1.3 \
    --location https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl.sha256 \
    --output /usr/local/src/kubectl/${KUBECTL_VERSION}/kubectl.sha256

WORKDIR /usr/local/src/kubectl/${KUBECTL_VERSION}
RUN echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check

RUN chmod +x /usr/local/src/kubectl/${KUBECTL_VERSION}/kubectl
RUN ln -snf /usr/local/src/kubectl/${KUBECTL_VERSION}/kubectl /usr/local/bin/kubectl

# kubesoloctl

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/kubesoloctl/${KUBESOLOCTL_VERSION}

RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/portainer/kubesolo/releases/download/v${KUBESOLOCTL_VERSION}/kubesoloctl-linux-amd64 \
    --output /usr/local/src/kubesoloctl/${KUBESOLOCTL_VERSION}/kubesoloctl-linux-amd64

RUN chmod +x /usr/local/src/kubesoloctl/${KUBESOLOCTL_VERSION}/kubesoloctl-linux-amd64
RUN ln -snf /usr/local/src/kubesoloctl/${KUBESOLOCTL_VERSION}/kubesoloctl-linux-amd64 /usr/local/bin/kubesoloctl

# kustomize

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/kustomize/${KUSTOMIZE_VERSION}

RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz \
    --output /usr/local/src/kustomize/${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz
RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/checksums.txt \
    --output /usr/local/src/kustomize/${KUSTOMIZE_VERSION}/checksums.txt

WORKDIR /usr/local/src/kustomize/${KUSTOMIZE_VERSION}
RUN sha256sum --ignore-missing --check checksums.txt

RUN tar --extract --gzip --file=/usr/local/src/kustomize/${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz --directory=/usr/local/src/kustomize/${KUSTOMIZE_VERSION} --no-same-owner
RUN chmod +x kustomize
RUN ln -snf /usr/local/src/kustomize/${KUSTOMIZE_VERSION}/kustomize /usr/local/bin/kustomize

# yq

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/yq/${YQ_VERSION}

RUN curl --proto '=https' --tlsv1.3 \
    --location https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64.tar.gz \
    --output /usr/local/src/yq/${YQ_VERSION}/yq_linux_amd64.tar.gz

RUN tar --extract --gzip --file=/usr/local/src/yq/${YQ_VERSION}/yq_linux_amd64.tar.gz --directory=/usr/local/src/yq/${YQ_VERSION} --no-same-owner

RUN chmod +x /usr/local/src/yq/${YQ_VERSION}/yq_linux_amd64
RUN ln -snf /usr/local/src/yq/${YQ_VERSION}/yq_linux_amd64 /usr/local/bin/yq

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        procps

# helm

COPY --from=build --chown=root:root /usr/local/bin/helm /usr/local/bin/helm

# k0sctl

COPY --from=build --chown=root:root /usr/local/bin/k0sctl /usr/local/bin/k0sctl

# k0s

COPY --from=build --chown=root:root /usr/local/bin/k0s /usr/local/bin/k0s

# kubectl

COPY --from=build --chown=root:root /usr/local/bin/kubectl /usr/local/bin/kubectl

# kubesoloctl

COPY --from=build --chown=root:root /usr/local/bin/kubesoloctl /usr/local/bin/kubesoloctl

# kustomize

COPY --from=build --chown=root:root /usr/local/bin/kustomize /usr/local/bin/kustomize

# yq

COPY --from=build --chown=root:root /usr/local/bin/yq /usr/local/bin/yq

# user and permissions

RUN groupadd --gid 10000 k8s && \
    useradd --comment 'k8s' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 k8s

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER k8s

CMD ["/bin/bash", "/cmd.sh"]
