FROM docker.io/debian:stable-slim AS build

ARG FORGEJO_VERSION="${FORGEJO_VERSION:-15.0.2}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg

# forgejo

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/forgejo

RUN curl --proto '=https' --tlsv1.2 \
        --location https://codeberg.org/forgejo/forgejo/releases/download/v${FORGEJO_VERSION}/forgejo-${FORGEJO_VERSION}-linux-amd64 \
        --output /usr/local/src/forgejo/forgejo-${FORGEJO_VERSION}-linux-amd64

RUN curl --proto '=https' --tlsv1.2 \
        --location https://codeberg.org/forgejo/forgejo/releases/download/v${FORGEJO_VERSION}/forgejo-${FORGEJO_VERSION}-linux-amd64.sha256 \
        --output /usr/local/src/forgejo/forgejo-${FORGEJO_VERSION}-linux-amd64.sha256

RUN curl --proto '=https' --tlsv1.2 \
        --location https://codeberg.org/forgejo/forgejo/releases/download/v${FORGEJO_VERSION}/forgejo-${FORGEJO_VERSION}-linux-amd64.asc \
        --output /usr/local/src/forgejo/forgejo-${FORGEJO_VERSION}-linux-amd64.asc

# https://codeberg.org/forgejo/gitea_proof
COPY --chown=root:root gpg /root/gpg
RUN gpg --no-default-keyring --keyring /root/keyring.gpg --fingerprint
RUN for key in /root/gpg/*; do \
        gpg --no-default-keyring --keyring /root/keyring.gpg --batch --import ${key}; \
    done

RUN gpg --no-default-keyring --keyring /root/keyring.gpg --verify /usr/local/src/forgejo/forgejo-${FORGEJO_VERSION}-linux-amd64.asc /usr/local/src/forgejo/forgejo-${FORGEJO_VERSION}-linux-amd64

WORKDIR /usr/local/src/forgejo
RUN sha256sum --ignore-missing --check forgejo-${FORGEJO_VERSION}-linux-amd64.sha256

RUN chmod 0755 /usr/local/src/forgejo/forgejo-${FORGEJO_VERSION}-linux-amd64

RUN ln -s /usr/local/src/forgejo/forgejo-${FORGEJO_VERSION}-linux-amd64 /usr/local/bin/forgejo

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        git \
        git-lfs \
        procps

# forgejo

COPY --from=build --chown=root:root /usr/local/bin/forgejo /usr/local/bin/forgejo

# user and permissions

RUN groupadd --gid 10000 forgejo && \
    useradd --comment 'forgejo' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 forgejo

RUN ln -snf /var/local/forgejo/ssh /home/forgejo/.ssh

RUN install --directory --owner=root --group=root --mode=0755 /var/local/forgejo && \
    install --directory --owner=forgejo --group=forgejo --mode=0700 /var/local/forgejo/ssh && \
    install --directory --owner=forgejo --group=forgejo --mode=0750 /var/local/forgejo/work

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER forgejo
STOPSIGNAL SIGINT

CMD ["/bin/bash", "/cmd.sh"]
