FROM docker.io/debian:stable-slim AS build

ARG COREDNS_VERSION="${COREDNS_VERSION:-1.14.7}"
ARG GO_CHECKSUM="${GO_CHECKSUM:-63d339f0da5ab53635a56f2490a7984dfe12dfcff22ad749f63edaf590168445}"
ARG GO_VERSION="${GO_VERSION:-1.27.1}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        git \
        gnupg

# go

ENV PATH="${PATH}:/usr/local/share/go/bin"

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/share/go \
    install --directory --owner=root --group=root --mode=0755 /usr/local/src/go

RUN curl --proto '=https' --tlsv1.3 \
        --location https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz \
        --output /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz
RUN curl --proto '=https' --tlsv1.3 \
        --location https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz.asc \
        --output /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.asc

# https://dl.google.com/linux/linux_signing_key.pub
COPY --chown=root:root gpg/go /root/gpg/go
RUN for key in /root/gpg/go/*; do \
        gpg --no-default-keyring --keyring /root/go.gpg --batch --import ${key}; \
    done
RUN gpg --no-default-keyring --keyring /root/go.gpg --fingerprint
RUN gpg --no-default-keyring --keyring /root/go.gpg --verify /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.asc /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz
RUN echo "${GO_CHECKSUM}  go${GO_VERSION}.linux-amd64.tar.gz" >/usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.sha256
WORKDIR /usr/local/src/go
RUN sha256sum --ignore-missing --check go${GO_VERSION}.linux-amd64.tar.gz.sha256

RUN tar --extract --gzip --file=/usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz --directory=/usr/local/share

# coredns

WORKDIR /usr/local/src
RUN git clone --depth 1 --branch v${COREDNS_VERSION} https://github.com/coredns/coredns.git

WORKDIR /usr/local/src/coredns
# Only compile defined plugins
COPY --chown=root:root plugin.cfg /usr/local/src/coredns/plugin.cfg
RUN go generate && \
    go build .
RUN chmod 0755 /usr/local/src/coredns/coredns
RUN ln -snf /usr/local/src/coredns/coredns /usr/local/bin/coredns

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        procps

# coredns

COPY --from=build --chown=root:root /usr/local/bin/coredns /usr/local/bin/coredns

# user and permissions

RUN groupadd --gid 10000 coredns && \
    useradd --comment 'coredns' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 coredns

RUN install --directory --owner=root --group=root --mode=0755 /var/local/coredns && \
    install --directory --owner=coredns --group=coredns --mode=0750 /var/local/coredns/config && \
    install --directory --owner=coredns --group=coredns --mode=0750 /var/local/coredns/zones

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER coredns

CMD ["/bin/bash", "/cmd.sh"]
