FROM docker.io/debian:stable-slim AS build

ARG LND_VERSION="${LND_VERSION:-0.21.0-beta}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        tar

# lnd

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/lnd

RUN curl --proto '=https' --tlsv1.3 \
        --location https://github.com/lightningnetwork/lnd/releases/download/v${LND_VERSION}/lnd-linux-amd64-v${LND_VERSION}.tar.gz \
        --output /usr/local/src/lnd/lnd-linux-amd64-v${LND_VERSION}.tar.gz

RUN curl --proto '=https' --tlsv1.3 \
        --location https://github.com/lightningnetwork/lnd/releases/download/v${LND_VERSION}/manifest-v${LND_VERSION}.txt \
        --output /usr/local/src/lnd/manifest-v${LND_VERSION}.txt

#RUN curl --proto '=https' --tlsv1.3 \
#        --location https://github.com/lightningnetwork/lnd/releases/download/v${LND_VERSION}/manifest-guggero-v${LND_VERSION}.sig \
#        --output /usr/local/src/lnd/manifest-guggero-v${LND_VERSION}.sig
RUN curl --proto '=https' --tlsv1.3 \
        --location https://github.com/lightningnetwork/lnd/releases/download/v${LND_VERSION}/manifest-roasbeef-v${LND_VERSION}.sig \
        --output /usr/local/src/lnd/manifest-roasbeef-v${LND_VERSION}.sig

# https://github.com/lightningnetwork/lnd/blob/master/scripts/keys
COPY --chown=root:root gpg /root/gpg
RUN for key in /root/gpg/*; do \
        gpg --no-default-keyring --keyring /root/keyring.gpg --batch --import ${key}; \
    done
RUN gpg --no-default-keyring --keyring /root/keyring.gpg --fingerprint

WORKDIR /usr/local/src/lnd
#RUN gpg --no-default-keyring --keyring /root/keyring.gpg --verify manifest-guggero-v${LND_VERSION}.sig manifest-v${LND_VERSION}.txt
RUN gpg --no-default-keyring --keyring /root/keyring.gpg --verify manifest-roasbeef-v${LND_VERSION}.sig manifest-v${LND_VERSION}.txt
RUN sha256sum --ignore-missing --check manifest-v${LND_VERSION}.txt

RUN tar --extract --gzip --file=/usr/local/src/lnd/lnd-linux-amd64-v${LND_VERSION}.tar.gz --directory=/usr/local/src/lnd

RUN mv /usr/local/src/lnd/lnd-linux-amd64-v${LND_VERSION}/lncli /usr/local/bin/lncli && \
    mv /usr/local/src/lnd/lnd-linux-amd64-v${LND_VERSION}/lnd /usr/local/bin/lnd

RUN chmod 0755 /usr/local/bin/lncli \
               /usr/local/bin/lnd

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        jq \
        procps

# lnd

COPY --from=build --chown=root:root /usr/local/bin/lncli /usr/local/bin/lncli
COPY --from=build --chown=root:root /usr/local/bin/lnd /usr/local/bin/lnd

# user and permissions

RUN groupadd --gid 10000 lnd && \
    useradd --comment 'lnd' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 lnd

RUN install --directory --owner=root --group=root --mode=0755 /var/local/lnd && \
    install --directory --owner=lnd --group=lnd --mode=0750 /var/local/lnd/data

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER lnd

CMD ["/bin/bash", "/cmd.sh"]
