FROM docker.io/debian:stable-slim AS build

ARG BITCOIN_CORE_VERSION="${BITCOIN_CORE_VERSION:-29.2}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        tar

# bitcoin-core

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/bitcoin-core

RUN curl --proto '=https' --tlsv1.3 \
        --location https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_CORE_VERSION}/bitcoin-${BITCOIN_CORE_VERSION}-x86_64-linux-gnu.tar.gz \
        --output /usr/local/src/bitcoin-core/bitcoin-${BITCOIN_CORE_VERSION}-x86_64-linux-gnu.tar.gz

RUN curl --proto '=https' --tlsv1.3 \
        --location https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_CORE_VERSION}/SHA256SUMS \
        --output /usr/local/src/bitcoin-core/SHA256SUMS

RUN curl --proto '=https' --tlsv1.3 \
        --location https://bitcoincore.org/bin/bitcoin-core-${BITCOIN_CORE_VERSION}/SHA256SUMS.asc \
        --output /usr/local/src/bitcoin-core/SHA256SUMS.asc

# https://github.com/bitcoin-core/guix.sigs/tree/main/builder-keys
COPY --chown=root:root gpg /root/gpg
RUN for key in /root/gpg/*; do \
        gpg --no-default-keyring --keyring /root/keyring.gpg --batch --import ${key}; \
    done
RUN gpg --no-default-keyring --keyring /root/keyring.gpg --fingerprint

WORKDIR /usr/local/src/bitcoin-core
RUN ["/bin/bash", "-c", "gpg --no-default-keyring --keyring /root/keyring.gpg --verify SHA256SUMS.asc 2> >(grep 'Good signature') || true"]

WORKDIR /usr/local/src/bitcoin-core
RUN sha256sum --ignore-missing --check SHA256SUMS

RUN tar --extract --gzip --file=/usr/local/src/bitcoin-core/bitcoin-${BITCOIN_CORE_VERSION}-x86_64-linux-gnu.tar.gz --directory=/usr/local/src/bitcoin-core

RUN chmod 0755 /usr/local/src/bitcoin-core/bitcoin-${BITCOIN_CORE_VERSION}/bin/bitcoin-cli \
        /usr/local/src/bitcoin-core/bitcoin-${BITCOIN_CORE_VERSION}/bin/bitcoind

RUN ln -snf /usr/local/src/bitcoin-core/bitcoin-${BITCOIN_CORE_VERSION}/bin/bitcoin-cli /usr/local/bin/bitcoin-cli && \
    ln -snf /usr/local/src/bitcoin-core/bitcoin-${BITCOIN_CORE_VERSION}/bin/bitcoind /usr/local/bin/bitcoind

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        procps

# bitcoin-core

COPY --from=build --chown=root:root /usr/local/bin/bitcoin-cli /usr/local/bin/bitcoin-cli
COPY --from=build --chown=root:root /usr/local/bin/bitcoind /usr/local/bin/bitcoind

# user and permissions

RUN groupadd --gid 10000 bitcoin-core && \
    useradd --comment 'bitcoin-core' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 bitcoin-core

RUN install --directory --owner=root --group=root --mode=0755 /var/local/bitcoin-core && \
    install --directory --owner=bitcoin-core --group=bitcoin-core --mode=0750 /var/local/bitcoin-core/db

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER bitcoin-core
STOPSIGNAL SIGINT

CMD ["/bin/bash", "/cmd.sh"]
