FROM docker.io/debian:stable-slim AS build

ARG GO_CHECKSUM="${GO_CHECKSUM:-2b2cfc7148493da5e73981bffbf3353af381d5f93e789c82c79aff64962eb556}"
ARG GO_VERSION="${GO_VERSION:-1.26.3}"
ARG MEMOS_VERSION="${MEMOS_VERSION:-0.29.0}"
ARG NODEJS_MAJOR_VERSION="${NODEJS_MAJOR_VERSION:-24}"
ARG PNPM_VERSION="${PNPM_VERSION:-latest-11}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        gcc \
        git \
        gnupg \
        lsb-release \
        musl-dev

# go

ENV PATH="${PATH}:/usr/local/share/go/bin"

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/share/go \
    install --directory --owner=root --group=root --mode=0755 /usr/local/src/go

RUN curl --proto '=https' --tlsv1.3 \
        --location https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz \
        --output /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz

RUN curl --proto '=https' --tlsv1.3 \
        --location https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz.asc \
        --output /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.asc

# https://dl.google.com/linux/linux_signing_key.pub
COPY --chown=root:root gpg /root/gpg
RUN gpg --no-default-keyring --keyring /root/keyring.gpg --fingerprint
RUN for key in /root/gpg/*; do \
        gpg --no-default-keyring --keyring /root/keyring.gpg --batch --import ${key}; \
    done

RUN gpg --no-default-keyring --keyring /root/keyring.gpg --verify /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.asc /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz

RUN echo "${GO_CHECKSUM}  go${GO_VERSION}.linux-amd64.tar.gz" >/usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.sha256

WORKDIR /usr/local/src/go
RUN sha256sum --ignore-missing --check go${GO_VERSION}.linux-amd64.tar.gz.sha256

RUN tar --extract --gzip --file=/usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz --directory=/usr/local/share

# npm

RUN apt update && \
    apt install -y --no-install-recommends \
        nodejs

# NOTE: Update SHA1 second-preimage resistance date for Sequoia GPG library
RUN sed -i 's@sha1.second_preimage_resistance.*@sha1.second_preimage_resistance = 2027-01-01@g' /usr/share/apt/default-sequoia.config

COPY --chown=root:root gpg/nodesource.gpg /etc/apt/trusted.gpg.d/nodesource.asc
RUN echo "deb https://deb.nodesource.com/node_${NODEJS_MAJOR_VERSION}.x nodistro main" >/etc/apt/sources.list.d/nodesource.list

RUN apt update && \
    apt install -y --no-install-recommends \
        nodejs

RUN if [ -n "${http_proxy}" ] ; then npm config set proxy ${http_proxy} ; fi
RUN if [ -n "${https_proxy}" ] ; then npm config set https-proxy ${https_proxy} ; fi

# pnpm

RUN npm install -g pnpm@${PNPM_VERSION}

# memos

WORKDIR /usr/local/src
RUN git clone --depth 1 --branch v${MEMOS_VERSION} https://github.com/usememos/memos.git

WORKDIR /usr/local/src/memos/web
RUN pnpm add -D vite
RUN pnpm build

WORKDIR /usr/local/src/memos
RUN cp -rp /usr/local/src/memos/web/dist /usr/local/src/memos/server/router/frontend
RUN go build -o memos ./cmd/memos

RUN chmod 0755 /usr/local/src/memos/memos

RUN ln -s /usr/local/src/memos/memos /usr/local/bin/memos

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        procps

# memos

COPY --from=build --chown=root:root /usr/local/bin/memos /usr/local/bin/memos

# user and permissions

RUN groupadd --gid 10000 memos && \
    useradd --comment 'memos' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 memos

RUN install --directory --owner=root --group=root --mode=0755 /var/local/memos && \
    install --directory --owner=memos --group=memos --mode=0750 /var/local/memos/db

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER memos

CMD ["/bin/bash", "/cmd.sh"]
