FROM docker.io/debian:stable-slim AS build

ARG GO_CHECKSUM="${GO_CHECKSUM:-990e6b4bbba816dc3ee129eaeaf4b42f17c2800b88a2166c265ac1a200262282}"
ARG GO_VERSION="${GO_VERSION:-1.26.2}"
ARG MEMOS_VERSION="${MEMOS_VERSION:-0.27.1}"
ARG NODEJS_MAJOR_VERSION="${NODEJS_MAJOR_VERSION:-24}"
ARG PNPM_VERSION"${PNPM_VERSION:-latest-10}"

# Set time zone
ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

# Install packages required in build stage
RUN apt update && \
    apt install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        curl \
        gcc \
        git \
        gnupg \
        lsb-release \
        musl-dev

# GO

# Set environment variables
ENV PATH="${PATH}:/usr/local/share/go/bin"

# Create directories for upstream source files
RUN install --directory --owner=root --group=root --mode=0755 /usr/local/share/go \
    install --directory --owner=root --group=root --mode=0755 /usr/local/src/go

# Download go archive
RUN curl --proto '=https' --tlsv1.2 \
        --location https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz \
        --output /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz

# Download go signature
RUN curl --proto '=https' --tlsv1.2 \
        --location https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz.asc \
        --output /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.asc

# Add keys to GPG keyring
# https://dl.google.com/linux/linux_signing_key.pub
COPY --chown=root:root gpg /root/gpg
RUN gpg --no-default-keyring --keyring /root/keyring.gpg --fingerprint
RUN for key in /root/gpg/*; do \
        gpg --no-default-keyring --keyring /root/keyring.gpg --batch --import ${key}; \
    done

# Verify go signature
RUN gpg --no-default-keyring --keyring /root/keyring.gpg --verify /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.asc /usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz

# Create go checksum
RUN echo "${GO_CHECKSUM}  go${GO_VERSION}.linux-amd64.tar.gz" >/usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz.sha256

# Verify go checksum
WORKDIR /usr/local/src/go
RUN sha256sum --ignore-missing --check go${GO_VERSION}.linux-amd64.tar.gz.sha256

# Unarchive go tarball
RUN tar --extract --gzip --file=/usr/local/src/go/go${GO_VERSION}.linux-amd64.tar.gz --directory=/usr/local/share

# NPM

# Add Node.js APT repository
COPY --chown=root:root gpg/nodesource.gpg /etc/apt/trusted.gpg.d/nodesource.asc
RUN echo "deb https://deb.nodesource.com/node_${NODEJS_MAJOR_VERSION}.x nodistro main" >/etc/apt/sources.list.d/nodesource.list

# Install npm
RUN apt update && \
    apt install -y --no-install-recommends \
        npm

# Set npm proxy/https-proxy if defined
RUN if [ -n "${http_proxy}" ] ; then npm config set proxy ${http_proxy} ; fi
RUN if [ -n "${https_proxy}" ] ; then npm config set https-proxy ${https_proxy} ; fi

# PNPM

# Install pnpm
RUN SHELL=bash npx pnpm@${PNPM_VERSION} dlx @pnpm/exe@${PNPM_VERSION} setup
# FIXME: Bash variable breaks pnpm internal version check: "Invalid package manager specification in CLI arguments"
#RUN corepack enable && corepack prepare "pnpm@${PNPM_VERSION}" --activate
RUN corepack enable && corepack prepare "pnpm@latest-10" --activate

# MEMOS

# Clone memos.git repository
WORKDIR /usr/local/src
RUN git clone --depth 1 --branch v${MEMOS_VERSION} https://github.com/usememos/memos.git

# Build front-end
WORKDIR /usr/local/src/memos/web
RUN pnpm add -D vite
RUN pnpm build

# Build back-end
WORKDIR /usr/local/src/memos
RUN cp -rp /usr/local/src/memos/web/dist /usr/local/src/memos/server/router/frontend
RUN go build -o memos ./cmd/memos/main.go

# Make memos executable
RUN chmod 0755 /usr/local/src/memos/memos

# Create memos symlink
RUN ln -s /usr/local/src/memos/memos /usr/local/bin/memos

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

# Set time zone
ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

# Install packages required in main stage
RUN apt update && \
    apt install -y --no-install-recommends \
        procps

# Copy binary from build stage
COPY --from=build --chown=root:root /usr/local/bin/memos /usr/local/bin/memos

# Create memos group and user
RUN groupadd --gid 10000 memos && \
    useradd --comment 'memos' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 memos

# Create directories for variable data
RUN install --directory --owner=root --group=root --mode=0755 /var/local/memos && \
    install --directory --owner=memos --group=memos --mode=0750 /var/local/memos/db

# Copy cmd.sh
COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER memos

CMD ["/bin/bash", "/cmd.sh"]
