FROM docker.io/debian:stable-slim AS build

ARG COSIGN_VERSION="${COSIGN_VERSION:-3.0.5}"
ARG STEP_CA_VERSION="${STEP_CA_VERSION:-0.30.2}"
ARG STEP_CLI_VERSION="${STEP_CLI_VERSION:-0.30.2}"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        jq \
        tar

# cosign

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/cosign

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-linux-amd64 \
        --output /usr/local/src/cosign/cosign-linux-amd64

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-linux-amd64.sigstore.json \
        --output /usr/local/src/cosign/cosign-linux-amd64.sigstore.json

RUN chmod 0755 /usr/local/src/cosign/cosign-linux-amd64

RUN ln -s /usr/local/src/cosign/cosign-linux-amd64 /usr/local/bin/cosign

RUN cosign verify-blob \
        --bundle /usr/local/src/cosign/cosign-linux-amd64.sigstore.json \
        --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com \
        --certificate-oidc-issuer https://accounts.google.com \
        /usr/local/src/cosign/cosign-linux-amd64

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign_checksums.txt \
        --output /usr/local/src/cosign/cosign_checksums.txt

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign_checksums.txt.sigstore.json \
        --output /usr/local/src/cosign/cosign_checksums.txt.sigstore.json

RUN cosign verify-blob \
        --bundle /usr/local/src/cosign/cosign_checksums.txt.sigstore.json \
        --certificate-identity keyless@projectsigstore.iam.gserviceaccount.com \
        --certificate-oidc-issuer https://accounts.google.com \
        /usr/local/src/cosign/cosign_checksums.txt

WORKDIR /usr/local/src/cosign
RUN sha256sum --ignore-missing --check cosign_checksums.txt

# step-ca

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/step-ca

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/smallstep/certificates/releases/download/v${STEP_CA_VERSION}/checksums.txt \
        --output /usr/local/src/step-ca/checksums.txt

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/smallstep/certificates/releases/download/v${STEP_CA_VERSION}/checksums.txt.sigstore.json \
        --output /usr/local/src/step-ca/checksums.txt.sigstore.json

RUN cosign verify-blob \
        --bundle /usr/local/src/step-ca/checksums.txt.sigstore.json \
        --certificate-identity-regexp "https://github\.com/smallstep/workflows/.*" \
        --certificate-oidc-issuer https://token.actions.githubusercontent.com \
        /usr/local/src/step-ca/checksums.txt

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/smallstep/certificates/releases/download/v${STEP_CA_VERSION}/step-ca_linux_${STEP_CA_VERSION}_amd64.tar.gz \
        --output /usr/local/src/step-ca/step-ca_linux_${STEP_CA_VERSION}_amd64.tar.gz

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/smallstep/certificates/releases/download/v${STEP_CA_VERSION}/step-ca_linux_${STEP_CA_VERSION}_amd64.tar.gz.sigstore.json \
        --output /usr/local/src/step-ca/step-ca_linux_${STEP_CA_VERSION}_amd64.tar.gz.sigstore.json

RUN cosign verify-blob \
        --bundle /usr/local/src/step-ca/step-ca_linux_${STEP_CA_VERSION}_amd64.tar.gz.sigstore.json \
        --certificate-identity-regexp "https://github\.com/smallstep/workflows/.*" \
        --certificate-oidc-issuer https://token.actions.githubusercontent.com \
        /usr/local/src/step-ca/step-ca_linux_${STEP_CA_VERSION}_amd64.tar.gz

WORKDIR /usr/local/src/step-ca
RUN sha256sum --ignore-missing --check checksums.txt

RUN tar --extract --gzip --file=/usr/local/src/step-ca/step-ca_linux_${STEP_CA_VERSION}_amd64.tar.gz --directory=/usr/local/src/step-ca

RUN ln -s /usr/local/src/step-ca/step-ca /usr/local/bin/step-ca

# step-cli

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/step-cli

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/smallstep/cli/releases/download/v${STEP_CLI_VERSION}/checksums.txt \
        --output /usr/local/src/step-cli/checksums.txt

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/smallstep/cli/releases/download/v${STEP_CLI_VERSION}/checksums.txt.sigstore.json \
        --output /usr/local/src/step-cli/checksums.txt.sigstore.json

RUN cosign verify-blob \
        --bundle /usr/local/src/step-cli/checksums.txt.sigstore.json \
        --certificate-identity-regexp "https://github\.com/smallstep/workflows/.*" \
        --certificate-oidc-issuer https://token.actions.githubusercontent.com \
        /usr/local/src/step-cli/checksums.txt

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/smallstep/cli/releases/download/v${STEP_CLI_VERSION}/step_linux_${STEP_CLI_VERSION}_amd64.tar.gz \
        --output /usr/local/src/step-cli/step_linux_${STEP_CLI_VERSION}_amd64.tar.gz

RUN curl --proto '=https' --tlsv1.2 \
        --location https://github.com/smallstep/cli/releases/download/v${STEP_CLI_VERSION}/step_linux_${STEP_CLI_VERSION}_amd64.tar.gz.sigstore.json \
        --output /usr/local/src/step-cli/step_linux_${STEP_CLI_VERSION}_amd64.tar.gz.sigstore.json

RUN cosign verify-blob \
        --bundle /usr/local/src/step-cli/step_linux_${STEP_CLI_VERSION}_amd64.tar.gz.sigstore.json \
        --certificate-identity-regexp "https://github\.com/smallstep/workflows/.*" \
        --certificate-oidc-issuer https://token.actions.githubusercontent.com \
        /usr/local/src/step-cli/step_linux_${STEP_CLI_VERSION}_amd64.tar.gz

WORKDIR /usr/local/src/step-cli
RUN sha256sum --ignore-missing --check checksums.txt

RUN tar --extract --gzip --file=/usr/local/src/step-cli/step_linux_${STEP_CLI_VERSION}_amd64.tar.gz --directory=/usr/local/src/step-cli

RUN ln -s /usr/local/src/step-cli/step_${STEP_CLI_VERSION}/bin/step /usr/local/bin/step

#---------------------------------------------------------------------

FROM docker.io/debian:stable-slim AS main

# Set time zone
ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        jq \
        procps

COPY --from=build --chown=root:root /usr/local/bin/step-ca /usr/local/bin/step-ca
COPY --from=build --chown=root:root /usr/local/bin/step /usr/local/bin/step

RUN groupadd --gid 10000 step-ca && \
    useradd --comment 'step-ca' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 step-ca

RUN install --directory --owner=root --group=root --mode=0755 /var/local/step-ca && \
    install --directory --owner=step-ca --group=step-ca --mode=0700 /var/local/step-ca/data

RUN ln -s /var/local/step-ca/data /home/step-ca/.step

COPY --chown=root:root cmd.sh /
RUN chmod 0755 /cmd.sh

USER step-ca
STOPSIGNAL SIGINT

CMD ["/bin/bash", "/cmd.sh"]
